server:
  port: ${TENDERING_PORT:8858}
  servlet:
    encoding:
      force: true

spring:
  application:
    name: ${@artifactId@:iserver-sentinel}

  # 引入Redis配置
  profiles:
    include: redis

  cloud:
    nacos:
      discovery:
        # 这里是您的 Nacos 相关连接信息，如：server-addr: 127.0.0.1:8848,一下配置我配置了 hosts 文件和环境变量方式
        server-addr: ${NACOS_HOST:iserver-nacos}:${NACOS_PORT:8848}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
logging:
  level:
    org:
      springframework:
        web: info
  file:
    name: ${user.home}/logs/csp/sentinel-dashboard.log
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'

auth:
  username: iserver
  password: asia8888
  filter:
    exclude-urls: /,/auth/login,/auth/logout,/registry/machine,/version,/actuator/**,/details
    exclude-url-suffixes: htm,html,js,css,map,ico,ttf,woff,png

sentinel:
  dashboard:
    version: ${@project.version@:1.8.6}
